services:
  postgres:
    container_name: postgres_container
    image: postgres:17.0-alpine3.20
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    networks:
      - postgres
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]

  home-solar-pi-server:
    container_name: home-solar-pi-server
    image: home-solar-pi-server:latest
    network_mode: "host"
    ports:
      - 5000:5000
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
